# Use an official Node.js runtime as the base image
FROM node:21-alpine
 
# Set the working directory in the container
WORKDIR /app
 
# Copy the package.json and package-lock.json files to the container
COPY package*.json ./
 
# Install project dependencies
RUN npm install
 
# Copy the rest of the project files to the container
COPY . .
 
# Build the Vite project for production
RUN npm run build
 
# Serve the built Vite project with a basic HTTP server
RUN npm install -g serve
 
# Expose the port for the HTTP server
EXPOSE 5000
 
# Start the HTTP server to serve the Vite app in production
CMD ["serve", "-s", "dist", "-l", "5000"]